# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-18 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20171120_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server_urls',
            options={'ordering': ['servertype'], 'verbose_name': 'URL', 'verbose_name_plural': 'URL'},
        ),
        migrations.AddField(
            model_name='server_urls',
            name='required_api',
            field=models.TextField(blank=True, verbose_name='API调用'),
        ),
        migrations.AddField(
            model_name='server_urls',
            name='required_database',
            field=models.TextField(blank=True, verbose_name='连接的数据库'),
        ),
        migrations.AlterField(
            model_name='server_urls',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='解释说明'),
        ),
    ]
