# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-09 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180718_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elasticsearch_Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP_Address', models.GenericIPAddressField()),
                ('Node_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='server_urls',
            options={'ordering': ['servertype', 'app_name'], 'verbose_name': 'URL', 'verbose_name_plural': 'URL'},
        ),
        migrations.AlterField(
            model_name='server_urls',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='server_urls',
            name='url',
            field=models.URLField(default='http://'),
        ),
    ]
