"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import time
from django.core.urlresolvers import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0chi6#=0=0#a9y+5*3arq49l6+7u62u!mk1@pcd25@wwb^=3s3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["10.181.3.91", "group1", "localhost"]

# User Model
#AUTH_USER_MODEL = 'userauth.CustomUser'


# Application definition

INSTALLED_APPS = [
    'userauth',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'services',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + "/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'NAME': os.path.join("D:\\DBdata", 'demo.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'
#LANGUAGE_CODE = 'zh-hans'


#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# userauth
# Login Model
# 添加函数 from django.core.urlresolvers import reverse_lazy
# 告诉 Django 用户登录成功后如果 contrib.auth.views.login 视图 view 没有获取到 next 参数将会默认重定向到哪个 URL
LOGIN_REDIRECT_URL = reverse_lazy('userauth:dashboard')
# 重定向用户登录的URL（例如：使用 login_required 装饰器（decorator））
LOGIN_URL = reverse_lazy('userauth:login')
# 重定向用户登出的URL
LOGOUT_URL = reverse_lazy('userauth:logout')

# SMTP config
# 默认选项
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 配置Django在标准输出中输出e-mail内容来代替通过SMTP服务发送邮件
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Default email address to use for various automated correspondence from the site manager(s).
DEFAULT_FROM_EMAIL = 'Notification@test.com'

EMAIL_HOST = 'smtp.sina.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = 'konvictzz@sina.com'
EMAIL_HOST_PASSWORD = '***'
EMAIL_USE_LOCALTIME = True
# 为邮件设置别名
# EMAIL_SUBJECT_PREFIX = '[Django-notification] '
# 与SMTP服务器通信时，是否启动TLS链接(安全链接)。默认是false
EMAIL_USE_TLS = True

# Logging
# https://docs.djangoproject.com/en/1.11/topics/logging/
# '''
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(levelname)s] [%(asctime)s] %(module)s %(process)d %(thread)d %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S %z'
        },
        'simple': {
            'format': '[%(levelname)s] %(asctime)s %(message)s'
        },
    },
    'filters': {
        #'special': {
        #    '()': 'project.logging.SpecialFilter',
        #    'foo': 'bar',
        #},
        #'require_debug_true': {
        #    '()': 'django.utils.log.RequireDebugTrue',
        #},
    },
    'handlers': {
        'request_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            #'filename': '/path/to/django/debug.log',
            'filename': 'log/request-' + time.strftime('%Y-%m-%d',time.localtime(time.time())) + '.log',
            'formatter': 'verbose',
        },
        'custom_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            #'filename': '/path/to/django/debug.log',
            'filename': 'log/custom.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['request_file','console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        #'django.request': {
        #    'handlers': ['console'],
        #    'level': 'DEBUG',
        #    'propagate': True,
        #},
        'myapp.views': {
            'handlers': ['custom_file','console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
# '''